#!/bin/sh
#
# Driver script for CCC reimplementation of GISTEMP in Python.  One
# day soon this file will become Python.
#
# Nick Barnes, Ravenbrook Limited, 2008-09-13.
#
# First draft: steps 0, 1, 2, 3 are in Python; steps 4, 5 still in
# FORTRAN.  Very rough cut.

fortran_compile=$FC
if [ "$FC" = "" ]
then echo "set an environment variable FC to the FORTRAN 90 compiler"
     echo "command, e.g. FC=gfortran42"
     exit
fi

# Compile the FORTRAN
mkdir -p bin
${fortran_compile} code/STEP4_5/SBBXotoBX.f -o bin/SBBXotoBX.exe
${fortran_compile} code/STEP4_5/zonav.f -o bin/zonav.exe
${fortran_compile} code/STEP4_5/annzon.f -o bin/annzon.exe

# Go.
mkdir -p work log result
echo "====> STEP 0 ===="
python code/step0.py
sort < work/v2.mean_comb.unsorted > work/v2.mean_comb

echo "====> STEP 1 ===="
python code/step1.py

echo "====> STEP 2 ===="
echo "converting text to binary file"
python code/text_to_binary.py `cat work/GHCN.last_year`

echo "breaking up Ts.bin into 6 zonal files"
python code/split_binary.py

echo "trimming Ts.bin1-6"
python code/trim_binary.py

echo "Making station list"
python code/invnt.py work/Ts.GHCN.CL > log/Ts.GHCN.CL.station.list

echo "Creating annual anomalies"
python code/toANNanom.py
python code/PApars.py 1000 20 > log/PApars.GHCN.CL.1000.20.log
python code/flags.py >> log/PApars.GHCN.CL.1000.20.log

echo "Applying peri-urban adjustment"
python code/padjust.py > log/padjust.log

echo "Making station list"
python code/invnt.py work/Ts.GHCN.CL.PA > log/Ts.GHCN.CL.PA.station.list

echo "====> STEP 3 ===="
python code/step3.py

echo "====> skipping STEP 4; see code/STEP4_5/do_comb_step4.sh ===="
python code/step4.py --verbose=1

echo "====> STEP 5 ===="
# GISS binary data files are big-endian, so ours are too, including
# the intermediate file generated by step3.py and the SBBX.HadR2 ocean
# file which comes out of STEP4.  We use GFORTRAN_CONVERT_UNIT to tell
# our code to treat all these files as big-endian.  This Will Not Work
# if the Fortran compiler is not GNU Fortran.

GFORTRAN_CONVERT_UNIT="big_endian:10,11,12" bin/SBBXotoBX.exe 100 0 > log/SBBXotoBX.log
GFORTRAN_CONVERT_UNIT="big_endian:10,11" bin/zonav.exe > log/zonav.Ts.ho2.GHCN.CL.PA.log
GFORTRAN_CONVERT_UNIT="big_endian:10,11,12" bin/annzon.exe  > log/annzon.Ts.ho2.GHCN.CL.PA.log

python code/vischeck.py result/GLB.Ts.ho2.GHCN.CL.PA.txt > result/google-chart.url
echo "See result/google-chart.url"
