#!/usr/bin/env python
# $URL$
# $Rev$
# stationmap.py
# David Jones, 2011-08-13, Climate Code Foundation.

"""
stationmap.py station-list

Plot the stations on a map (SVG output).

*station-list* names a file of station identifiers.  The file is scanned
and any line starting with 11 alphanumeric characters (no spaces) is
used.  The location metadata for the stations is taken from the file
input/v2.inv.
"""

import re
import sys

# ccc-gistemp
import gio

def map(inp, out=sys.stdout, land=None):
    """Plot stations on map.  *inp* is a list of filenames specifying
    the station IDs.  *land*, if specified, names an SVG file for
    the land to be used as background (this option is really only
    expected to work with certain specially prepared SVG files).
    """

    out.write("""<svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
""")
    out.write("<!-- Generated by Clear Climate Code -->\n")
    out.write("""<defs>
  <style type="text/css">
    g.land { stroke: none; fill: gold }
    g.stations {
      stroke: green; stroke-width: 1.4; stroke-linecap: round; fill: none
    }
    text { fill: black; font-family: Verdana }
  </style></defs>
""")

    if land:
	land = open(land).read()
        landfrag = re.search(r'<g class=.land..*</g>', land, re.DOTALL)
        out.write(landfrag.group())
	out.write("\n")

    out.write("<g class='stations'>\n")
    out.write("<g transform='translate(0, 360) scale(1,-1)'>\n")
    for station in stations(inp):
	lat,lon = station.lat,station.lon
        lon += 180.0
        lat += 90.0
	lat,lon = [x*2.0 for x in (lat,lon)]
        out.write("<path d='M%.2f %.2fl0 0' />\n" % (lon,lat))
    out.write("</g>\n"*2)
    out.write("</svg>\n")

def stations(filenames):
    """Yield the metadata for each station listed in *filenames*."""

    filename = filenames[0]

    ids = set(l[:11] for l in open(filename) if re.match(r'\w{11}', l))
    meta = gio.station_metadata(path='input/v2.inv')
    lost = False
    for id in ids:
        if id in meta:
            yield meta[id]
        else:
            lost = True
    if lost:
        raise Exception("Couldn't find metadata for some stations.")


def main(argv=None):
    # http://docs.python.org/release/2.4.1/lib/module-getopt.html
    import getopt
    import sys
    if argv is None:
        argv = sys.argv

    option = {}
    opts,arg = getopt.getopt(argv[1:], '', ['land='])
    for o,v in opts:
        if o == '--land':
            option['land'] = v

    map(arg, **option)

if __name__ == '__main__':
    main()
